styles.templates.layoutRootPath: 'EXT:stepping_stone_site_package/Resources/Private/ContentElements/Layouts/'
styles.templates.partialRootPath: 'EXT:stepping_stone_site_package/Resources/Private/ContentElements/Partials/'
styles.templates.templateRootPath: 'EXT:stepping_stone_site_package/Resources/Private/ContentElements/Templates/'

page.tracking.google.trackingID: ''
page.tracking.google.anonymizeIp: '1'

config.no_cache: '0'
config.removeDefaultJS: '0'
config.admPanel: '1'
config.prefixLocalAnchors: 'all'
config.sendCacheHeaders: '1'
