name: ndz/membershortcut
typeName: ndz_membershortcut
group: stepping-stone
prefixFields: true
prefixType: full
basics:
  - TYPO3/Appearance
fields:
  - identifier: heading
    type: Palette
    label: Headlines
    fields:
    - identifier: header
      useExistingField: true
      type: Textarea
    - identifier: header_layout
      useExistingField: true
    - identifier: header_style
      useExistingField: true
      type: Select
  - identifier: record_select
    type: Relation
    label: Members
    allowed: 'tx_ndz_teammember, tx_ndz_consulting'