name: ndz/event
table: tx_ndz_event
prefixFields: false
labelField: title
security:
  ignorePageTypeRestriction: true
fields:
  - identifier: title
    type: Text
    label: Title
    required: true
  - identifier: startdate
    type: DateTime
    format: datetime
    label: Start date
    default: '2023-02-11 12:00:00'
    required: true
  - identifier: enddate
    type: DateTime
    format: datetime
    label: End date
    default: '2023-02-11 12:00:00'
    required: true
  - identifier: venue
    type: Text
    label: Venue
    required: true
  - identifier: address
    type: Text
    label: Address
    required: true
  - identifier: zip
    type: Number
    label: Postcode
    range:
      lower: 1000
      upper: 9999
    required: true
  - identifier: location
    type: Text
    label: Location
    required: true
  - identifier: description
    type: Textarea
    label: Description
    required: true
  - identifier: map
    type: File
    label: Map
    maxitems: 1
    allowed: jpg,jpeg,webp,gif,png
