services:
  IndizDigitalGmbh\SteppingStoneSitePackage\:
    resource: '../Classes/*'
    autowire: true
    autoconfigure: true

  IndizDigitalGmbh\SteppingStoneSitePackage\Middleware\BrowserLanguageRedirectMiddleware:
    public: false