name: ndz/columns
typeName: ndz_columns
group: stepping-stone
prefixFields: true
prefixType: full
basics:
  - TYPO3/Appearance
fields:
  - identifier: overline
    type: Palette
    label: Headlines
    fields:
      - identifier: subheader
        useExistingField: true
        label: Overline
  - identifier: heading
    type: Palette
    fields:
      - identifier: header
        useExistingField: true
        type: Textarea
      - identifier: header_layout
        useExistingField: true
      - identifier: header_style
        useExistingField: true
        type: Select
  - identifier: columns
    type: Palette
    fields:
      - identifier: col1
        label: First Column
        type: Collection
        maxitems: 1
        fields:
          - identifier: bodytext
            type: Textarea
            enableRichtext: true
            richtextConfiguration: custom
      - identifier: col2
        label: Second Column
        type: Collection
        maxitems: 1
        fields:
          - identifier: bodytext
            type: Textarea
            enableRichtext: true
            richtextConfiguration: custom
      - identifier: col3
        label: Third Column
        type: Collection
        maxitems: 1
        displayCond: 'FIELD:colnumbers:=:3cols'
        onChange: reload
        fields:
          - identifier: bodytext
            type: Textarea
            enableRichtext: true
            richtextConfiguration: custom
  - identifier: settingsTab
    type: Tab
    label: Settings
  - identifier: ce_settings
    type: Palette
    label: Content Element Settings
    fields:
      - identifier: colnumbers
        type: Select
        label: Number of columns
        renderType: selectSingle
        items:
        - label: '2 Columns'
          value: 2cols
        - label: '3 Colunns'
          value: 3cols
